version: '2.1'

services:
  web:
    build: .
    command: bash -c "bundle install && rails s -p 3001 -b 0.0.0.0"
    volumes:
      - .:/app
      - gem-cache:/gems
    ports:
      - '3001:3001'
    environment: &default_environment
      DATABASE_URL: 'postgres://postgres:@postgres:5432'
      OS: 'windows'
    depends_on:
      - postgres

  postgres:
    image: postgres:9.5
    ports:
      - '5432'

volumes:
  gem-cache: